### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by kaday506s** [OokGIT/itstep-study#1]
https://github.com/OokGIT/itstep-study/blob/dfffb0d91a405ef75155917aefca6e89b82829e7/2.%20Lesson/file01.py#L17

В данном случае у тебя в будет заходить в первый блок (потому что if True) -> Нужно проверить значение dig1.isdigit() - данная функция вернет либо True / False и программа певедет себя по разному

**Comment by OokGIT** [comment]
Спасибо! Да, это ж я вчера на занятии недоделал, ещё есть что править )))

**Comment by OokGIT** [comment]
Переписал. 
Не совсем уверен в красоте кода в конструкции 
if dig1.isdigit() is True:
    dig1 = int(dig1)
#    print (dig1)
else:
    print('введено не число')
    exit()

Но, по крайней мере, проверки работают, операции над двумя числами проводятся.
Думаю, как освою до конца теорию по "Pyton_урок02", будет лучше. ))

https://github.com/OokGIT/itstep-study/blob/main/2.%20Lesson/file01.py
