### ISSUE TITLE
dig1.isdigit() is True

### ISSUE THREAD

**Issue by kaday506s** [OokGIT/itstep-study#2]
https://github.com/OokGIT/itstep-study/blob/a776fc9f40614535979a17793b4273d1317d3a1b/2.%20Lesson/file01.py#L9

Тут не стоит сравнивать is True. Сама функция вернет уже либо True/False. А ты потом еще делаешь одну лишению проверку которая в свою очередь снова вернет Либо True / False.

**Comment by OokGIT** [comment]
Да, было такое ))) Спасибо!
