### ISSUE TITLE
operations = str(input("Выберите одну из математических операций: (+  -  *  /)\n"))

### ISSUE THREAD

**Issue by kaday506s** [OokGIT/itstep-study#3]
https://github.com/OokGIT/itstep-study/blob/a776fc9f40614535979a17793b4273d1317d3a1b/2.%20Lesson/file01.py#L2

Тут не стоит input оборачивать в str() - так как input  вернет уже str

**Comment by OokGIT** [comment]
Спасибо, поправил!
